es_master:
  image: lucasko/elasticsearch
  ports:
    - "9200:9200" 
    - "9300:9300" 
  volumes:
    - $PWD/config-master:/usr/share/elasticsearch/config 
  restart: always


es_slave:
  image: lucasko/elasticsearch
  links:
    - es_master
  volumes:
    - $PWD/config-slave:/usr/share/elasticsearch/config
  command: "-Des.discovery.zen.ping.unicast.hosts=es_master:9300"
  restart: always



